### ISSUE TITLE
Error Route is already handled! after upgrading to 1.0.3

### ISSUE THREAD

**Issue by aleehedl** [valendres/playwright-msw#31] opened 2022-10-31 11:04 UTC
Hi, 

After upgrading `playwright-msw` to version 1.0.3, some of my msw rest handlers raise the following error after the handler has settled:

```
    route.fulfill: Route is already handled!

       at node_modules/playwright-msw/lib/server.js:32

      30 |     const handleMockResponse = ({ status, headers, body }) => {
      31 |         var _a;
    > 32 |         route.fulfill({
         |               ^
      33 |             status,
      34 |             body: body !== null && body !== void 0 ? body : undefined,
      35 |             contentType: (_a = headers.get("content-type")) !== null && _a !== void 0 ? _a : undefined,
```

At the moment I'm unable to provide a minimal example to reproduce the error. The version of msw is 0.46.1, and the the calls are made from a React application. With `playwright-msw=1.0.0` the same code works fine.

**Comment by valendres** [comment] 2022-11-01 03:57
Hey @aleehedl, thanks for raising this. My apologies for running into this issue. I suspect a recent change to how we handle routes may have caused this: https://github.com/valendres/playwright-msw/commit/d222fbba7eb931f473fe8a744238428620e4d143

In this change, we now wait for a route to actually be fulfilled before executing another handler. If I had to guess, it's likely that there are multiple MSW handlers matching the same route, and it's running into a race condition.

I've recently been working on a significant refactor for how the routing logic works, instead of intercepting all API calls and comparing them with the MSW handlers, it now only mocks API calls that are specified by the handlers.  This new implementation may fix your issue. I'm wondering if you'd consider trying it out [2.0.0-beta.0](https://www.npmjs.com/package/playwright-msw/v/2.0.0-beta.0)?

Regardless, I'll look into what can be done to resolve this issue as it's not ideal that the current version has a bug in it which prevents tests from running.

**Comment by valendres** [comment] 2022-11-07 10:33
Hey @aleehedl. I haven't been able to reproduce this issue in my own testing. However, a significant refactor to how routing works was recently published in [v2.0.0](https://www.npmjs.com/package/playwright-msw/v/2.0.0). Given that you're unable to provide a minimal example that reproduces this error, I'm wondering whether you'd be able to try out this new version and see if it addresses your issue?

Please note that this version also adds support for GraphQL, which resulted in a breaking change to the createWorkerFixture interface. The [V2 Migration Guide](https://github.com/valendres/playwright-msw/blob/main/packages/playwright-msw/README.md#v2-migration-guide) should serve as a good reference when upgrading 🙂

**Comment by aleehedl** [comment] 2022-11-07 17:39
Thanks for the heads up, @valendres. I'll try this as soon as possible!

**Comment by valendres** [comment] 2023-02-04 06:33
@aleehedl, I'm unsure if you ever got around to testing this, but I have finally been able to reproduce this issue locally. It seems to be a compatibility issue with older versions of MSW (`< 0.47.3`). 

Simple solution is to update to the latest versions of `msw` and `playwright-msw` :) 

Closing this issue now. Happy to re-open if it pops up again.

**Closed by valendres** 2023-02-04 06:33 UTC

**Comment by aleehedl** [comment] 2023-02-04 20:18
Thanks for the response. I'm currently stuck with `msw@< 1.0.0` due to a pinned peer dependency in another package, so unable to update to the latest versions just now. Hopefully I will get to it soon.

**Comment by balpreetK** [comment] 2024-04-07 23:24
what if someone is not using msw and just using playwright in automation framework??
